"""Initial migration: Create all tables

Revision ID: 223d53df8301
Revises: 
Create Date: 2025-09-06 21:37:42.931293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223d53df8301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
