"""Update models to use strings instead of UUIDs for SQLite compatibility

Revision ID: 2ad52b731a61
Revises: 223d53df8301
Create Date: 2025-09-06 21:40:12.878427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad52b731a61'
down_revision = '223d53df8301'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
